interface Size {
    weight: string;
    family: string;
    size: string;
    lineHeight: string;
    letterSpacing: string;
}

interface TypographySizes {
    [key: string]: Size;
}

export const types = [
    "display-lg",
    "display-md",
    "display-sm",
    "title-2xl",
    "title-xl",
    "title-lg",
    "title-md",
    "title-sm",
    "title-xs",
    "body-lg",
    "body-md",
    "body-sm",
    "caption-lg",
    "caption-md",
    "label-lg",
    "label-md",
    "label-sm",
    "label-xs",
];

export const xxlSize: TypographySizes = {
    "display-lg": {
        family: "Inter",
        weight: "600",
        size: "72px",
        lineHeight: "100px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "Inter",
        weight: "600",
        size: "64px",
        lineHeight: "88px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "Inter",
        weight: "600",
        size: "56px",
        lineHeight: "80px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "Inter",
        weight: "600",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "Inter",
        weight: "600",
        size: "42px",
        lineHeight: "60px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "Inter",
        weight: "600",
        size: "36px",
        lineHeight: "52px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "Inter",
        weight: "600",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "Inter",
        weight: "600",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "Inter",
        weight: "400",
        size: "24px",
        lineHeight: "36px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "Inter",
        weight: "400",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "Inter",
        weight: "400",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "Inter",
        weight: "600",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "caption-md": {
        family: "Inter",
        weight: "500",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "Inter",
        weight: "700",
        size: "24px",
        lineHeight: "36px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "Inter",
        weight: "700",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "label-sm": {
        family: "Inter",
        weight: "500",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "Inter",
        weight: "500",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
};

export const xlSize: TypographySizes = {
    "display-lg": {
        family: "Inter",
        weight: "600",
        size: "64px",
        lineHeight: "88px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "Inter",
        weight: "600",
        size: "56px",
        lineHeight: "80px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "Inter",
        weight: "600",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "Inter",
        weight: "600",
        size: "36px",
        lineHeight: "52px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "Inter",
        weight: "600",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "Inter",
        weight: "600",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "Inter",
        weight: "600",
        size: "18px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "Inter",
        weight: "600",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "Inter",
        weight: "400",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "Inter",
        weight: "400",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "Inter",
        weight: "400",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "Inter",
        weight: "600",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-md": {
        family: "Inter",
        weight: "500",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "Inter",
        weight: "700",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "Inter",
        weight: "700",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-sm": {
        family: "Inter",
        weight: "500",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "Inter",
        weight: "500",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const lgSize: TypographySizes = {
    "display-lg": {
        family: "Inter",
        weight: "600",
        size: "56px",
        lineHeight: "80px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "Inter",
        weight: "600",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "Inter",
        weight: "600",
        size: "40px",
        lineHeight: "56px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "Inter",
        weight: "600",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "Inter",
        weight: "600",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "Inter",
        weight: "600",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "Inter",
        weight: "600",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "Inter",
        weight: "600",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "Inter",
        weight: "400",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "Inter",
        weight: "400",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "Inter",
        weight: "400",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "Inter",
        weight: "600",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-md": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "Inter",
        weight: "700",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "Inter",
        weight: "700",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-sm": {
        family: "Inter",
        weight: "500",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const mdSize: TypographySizes = {
    "display-lg": {
        family: "Inter",
        weight: "600",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "Inter",
        weight: "600",
        size: "40px",
        lineHeight: "56px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "Inter",
        weight: "600",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "Inter",
        weight: "600",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "Inter",
        weight: "600",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "Inter",
        weight: "600",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "Inter",
        weight: "600",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "Inter",
        weight: "600",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "Inter",
        weight: "400",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "Inter",
        weight: "400",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "Inter",
        weight: "400",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "Inter",
        weight: "600",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-md": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "Inter",
        weight: "700",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "Inter",
        weight: "700",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-sm": {
        family: "Inter",
        weight: "500",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const smSize: TypographySizes = {
    "display-lg": {
        family: "Inter",
        weight: "600",
        size: "40px",
        lineHeight: "56px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "Inter",
        weight: "600",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-0.5px",
    },
    "title-xl": {
        family: "Inter",
        weight: "600",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-lg": {
        family: "Inter",
        weight: "600",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-md": {
        family: "Inter",
        weight: "600",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "title-sm": {
        family: "Inter",
        weight: "600",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "title-xs": {
        family: "Inter",
        weight: "600",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-lg": {
        family: "Inter",
        weight: "400",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "Inter",
        weight: "400",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "Inter",
        weight: "400",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "Inter",
        weight: "600",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-md": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "Inter",
        weight: "700",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "Inter",
        weight: "700",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-sm": {
        family: "Inter",
        weight: "500",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const xsSize: TypographySizes = {
    "display-lg": {
        family: "Inter",
        weight: "600",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-0.5px",
    },
    "display-md": {
        family: "Inter",
        weight: "600",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-0.5px",
    },
    "display-sm": {
        family: "Inter",
        weight: "600",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "title-2xl": {
        family: "Inter",
        weight: "600",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "title-xl": {
        family: "Inter",
        weight: "600",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "title-lg": {
        family: "Inter",
        weight: "600",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "title-md": {
        family: "Inter",
        weight: "600",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "title-sm": {
        family: "Inter",
        weight: "600",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "title-xs": {
        family: "Inter",
        weight: "600",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-lg": {
        family: "Inter",
        weight: "400",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "Inter",
        weight: "400",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "Inter",
        weight: "400",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "Inter",
        weight: "600",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-md": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "Inter",
        weight: "700",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "Inter",
        weight: "700",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-sm": {
        family: "Inter",
        weight: "500",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "Inter",
        weight: "500",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const breakpoints = {
    xxl: "3840px",
    xl: "2559px",
    lg: "1919px",
    md: "1439px",
    sm: "1023px",
    xs: "767px",
};